server:
  port: 
  log_level: 

db:
  neo4j:
    host: 
    port: 
    username: 
    password: 
  mysql:
    host: 
    port: 
    username: 
    password: 
    db_name: 

model:
  api_key: 

jwt:
  secret_key: 